/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import processing.core.PApplet;

class AppTest {
    @Test 
    public void simpleTest() {
        App testApp = new App();
        PApplet.runSketch(new String[] {"App"}, testApp);
        testApp.getGameManager().readJson("configTest.json");
        testApp.setup();
        assertNotNull(testApp);
        assertNotNull(testApp.getWaka());
        Waka startWaka = testApp.getWaka();
        assertEquals(testApp.getGhosts().size(), 4);
        assertNotNull(testApp.getMap());
        assertNotNull(testApp.getGameManager());
        testApp.resetGame();
        Coordinate startWakaCoord = startWaka.getCoord();
        Coordinate testCoord = testApp.getWaka().getCoord();
        assertTrue(startWakaCoord.equals(testCoord));
    }
}
